In [1]:
import pandas as pd
import numpy as np

In [2]:
# 데이터를 분석하려면 데이터프레임형태로 만들면 됨.
# 행(인스턴스, 실제값), 열(속성, 특성)을 가지는 2차원이 되게 됨.
# 파이썬에서는 데이터분석시 사용하는 2차원을 다루기 위해서 클래스(부품)를 만들었음.

In [3]:
dics = {"name" : ["홍길동","박길동","김길동","송길동"], "age":[10,20,30,40]}
df = pd.DataFrame(dics)
df

name  age
0  홍길동   10
1  박길동   20
2  김길동   30
3  송길동   40

In [23]:
name_values = ["홍길동","박길동","김길동","송길동"]
age_values = [10,20,30,40]
df3 = pd.DataFrame({"name": name_values, "age": age_values})
df3

name  age
0  홍길동   10
1  박길동   20
2  김길동   30
3  송길동   40

In [4]:
# 인덱스가 자동증가해서 붙어있는 부품 : 데이터프레임
df.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
df_index = df.index.tolist() #인덱스만 목록으로 가지고 오고 싶으면 list로 변경해서 사용
df_index

[0, 1, 2, 3]

In [5]:
type(df.index) #RangeIndex 부품,class

pandas.core.indexes.range.RangeIndex

In [6]:
df.name

0    홍길동
1    박길동
2    김길동
3    송길동
Name: name, dtype: object

In [25]:
# 시리즈를 데이터프레임으로 변경할 수 있다.
df_name = df['name'].to_frame()
df_name
type(df_name)

pandas.core.frame.DataFrame

In [7]:
df['name']

0    홍길동
1    박길동
2    김길동
3    송길동
Name: name, dtype: object

In [9]:
type(df['name']) #데이터프레임안에서 

pandas.core.series.Series

In [12]:
# 데이터프레임은 RangeIndex, Series의 결합임

In [13]:
# 시리즈는 인덱스와 array객체와 결합

In [14]:
df['name'].index

RangeIndex(start=0, stop=4, step=1)

In [15]:
df_name_list = df['name'].index.tolist()
df_name_list

[0, 1, 2, 3]

In [16]:
df['name'].values

array(['홍길동', '박길동', '김길동', '송길동'], dtype=object)

In [17]:
df['name'].values.tolist()

['홍길동', '박길동', '김길동', '송길동']

In [18]:
df_name_values = df['name'].values.tolist()
df_name_values

['홍길동', '박길동', '김길동', '송길동']

In [19]:
# Series를 리스트로 변환, 인덱스가 생략한 형태의 리스트가 됨.
df_name_values2 = df['name'].tolist() 
df_name_values2

['홍길동', '박길동', '김길동', '송길동']

# 데이터프레임을 만드는 방법
***
### dic사용
### csv, excel파일 읽어오기
### df에 values, column을 지정

In [22]:
df2 = pd.DataFrame(data = [['홍길동',100],['김길동',200]], columns=['name', 'age'])
df2

name  age
0  홍길동  100
1  김길동  200

In [26]:
df2.columns

Index(['name', 'age'], dtype='object')

In [27]:
df2.columns.tolist()

['name', 'age']

In [28]:
data = [100,200,300]
sum(data)

600

In [31]:
max(data)

300

In [ ]:
# ndarray
# n : 1,2,3
# d : 차원
# array : 배열

In [33]:
arr1 = np.arange(15) #0~14까지의 연속된 값을 만들어주는 함수, 1차원
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
arr1_reshape = arr1.reshape(3, 5) #원하는 차원으로(모양으로) 변환
arr1_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
type(arr1_reshape)

numpy.ndarray

In [38]:
# mask
mask = np.zeros(5)
mask

array([0., 0., 0., 0., 0.])

In [44]:
mask2 = np.zeros((3, 4))
mask2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
arr2 = np.array([
    [1,2,3],[4,5,6]
    ], dtype=np.float64) 
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
arr3 = np.array([
    [7,8,9],[10,11,12]
    ], dtype=np.float64) 
arr3

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [41]:
# 행렬의 연산을 할 수 있음.
arr2 + arr3

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [42]:
arr2 * arr3

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [43]:
arr2 - arr3

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [45]:
np.random.rand(20)

array([0.20838082, 0.12144406, 0.02379013, 0.85628541, 0.92642051,
       0.39309015, 0.22559108, 0.33621107, 0.07607785, 0.8566236 ,
       0.19080974, 0.23759248, 0.20096905, 0.5731318 , 0.9402696 ,
       0.39137012, 0.02041778, 0.158796  , 0.25114425, 0.52368975])

In [49]:
np.random.randint(10)

8